### ISSUE TITLE
Declare a simple "Module" for TypeScripe usage in Angular

### ISSUE THREAD

**Issue by Johannes-Schiel** [LottieFiles/lottie-interactivity#98]
## Overview

...

## Motivation

> What inspired this enhancement? What makes you think this should be included?

I love this projects and use it in a few Vue projects with a realy simple update we can make it work in angular just as well :).

### The Problem

If you install the project in angular you get this error message.

```
Error: src/app/shared/components/lottie/lottie.component.ts:3:24 - error TS7016: Could not find a declaration file for module '@lottiefiles/lottie-interactivity'. 'C:/Dev/.../node_modules/@lottiefiles/lottie-interactivity/dist/lottie-interactivity.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lottiefiles__lottie-interactivity` if it exists or add a new declaration (.d.ts) file containing `declare module '@lottiefiles/lottie-interactivity';`

3 import { create } from '@lottiefiles/lottie-interactivity';
```

We need a new file in a new directory

`types/lottie-interactivity.d.ts`

```typescript
declare module '@lottiefiles/lottie-interactivity';
```

after that the types has to be defined in the package.json

```json
{
   ...
   "types": "./types/lottie-interactivity.d.ts",
   ...
}
```

After that in the release/build step the new folder with the new d.ts file has to be exported to the npm package. I tested it on my projects with npm link its just work with not further changes.

I hope this is a nice improvement :) and thx for your work

## Labels

- [x] Add the `Type: Enhancement` label to this issue.

**Comment by samuelOsborne** [comment]
Thanks for submitting this @Johannes-Schiel , I'll try and implement it asap :)

**Comment by Johannes-Schiel** [comment]
thx if i can help i can easly create a pull request

**Comment by Johannes-Schiel** [comment]
@samuelOsborne i dont wont to rush but do you have a plan when you have time to create a new version? If you have no time at this moment, i could create a PR so you just have to check the code ? I need that feature for my new project :D

**Comment by Andreea-G** [comment]
Hi any updates on this? I also need it for my project. Thanks!

**Comment by Johannes-Schiel** [comment]
I don't think thats a fix has been added yet, so i created a fork of this package and fixed it myself

**Comment by samuelOsborne** [comment]
Hey  @Andreea-G  @Johannes-Schiel types should be added in version v.1.6.2!

**Comment by Johannes-Schiel** [comment]
Hello @samuelOsborne  ahh nice, do you have a timeline when this will be release? or as i asked in a previous comment i can help :)

**Comment by samuelOsborne** [comment]
ah my b @Johannes-Schiel its out now via npm

**Comment by Johannes-Schiel** [comment]
sooo sadly after update to 1.6.2 i get another error

**Error: node_modules/@lottiefiles/lottie-interactivity/dist/lottie-interactivity.d.ts:5:39 - error TS2339: Property 'mode' does not exist on type '{ player: string; }'**

any idear where this is coming from?

**Comment by jockgu** [comment]
> sooo sadly after update to 1.6.2 i get another error
> 
> **Error: node_modules/@lottiefiles/lottie-interactivity/dist/lottie-interactivity.d.ts:5:39 - error TS2339: Property 'mode' does not exist on type '{ player: string; }'**
> 
> any idear where this is coming from?

This needs to be updated to 

`
    constructor({ actions, container, mode, player, ...options }?: {
        actions: any;
        container: any;
        mode: any;
        player: string;
    });
`
